//污染物信息数据
var wuranwuData = [
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"氨气",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"三甲胺",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"硫化氢",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"甲硫醚",
        "nongdu":'2.70',                      
    },
    
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"苯乙烯",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"二甲二硫",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"二硫化碳",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"乙苯",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"丙醛",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"丁醛",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"戊醛",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"乙酸乙酯",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"乙酸丁酯",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"甲基乙基酮",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"甲基异丁基",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"甲基异丁基酮",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"乙醛",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"丙烯酸甲酯",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"酚类",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"甲基丙烯酸甲酯",
        "nongdu":'2.70',                      
    },
    {
        "wuranyuanId":"W05",        
        "wuranwuId":"12334",
        "name":"臭气浓度",
        "nongdu":'2.70',                      
    },
    //以下为准
    
]
    