
//XXX阳光小区瑟凤河污染事件列表数据
var minganData = [
	{
        "id":"M1",        
        "name":"振业峦山谷",
        "jingdu":"114.27283",
        "weidu":"22.693079",
        "nongdu":"91",        
        "describe":"有明显烧焦味",        
        "date":"2018-11-01",
        "wuranwu":[
                {
                    name:"氨气",
                    value:"2.8",
                },
                {
                    name:"三甲胺",
                    value:"94.22",
                },
                {
                    name:"硫化氢",
                    value:"7.9",
                }
            ]                
    },

	{
        "id":"M2",        
        "name":"峦山美地",
        "jingdu":"114.275702",
        "weidu":"22.695967",
        "nongdu":"88",        
        "describe":"轻微异味",        
        "date":"2018-11-02",
        "wuranwu":[
                {
                    name:"甲硫醚",
                    value:"2.7",
                },
                {
                    name:"苯乙烯",
                    value:"93.2",
                },
                {
                    name:"二硫化碳",
                    value:"7.9",
                }
            ]                
    },
	{
        "id":"M3",        
        "name":"联合家园",
        "jingdu":"114.289643",
        "weidu":"22.702035",
        "nongdu":"77",        
        "describe":"轻微异味",        
        "date":"2018-11-03",
        "wuranwu":[
                {
                    name:"乙苯",
                    value:"2.17",
                },
                {
                    name:"二硫化碳",
                    value:"94.2",
                },
                {
                    name:"丁醛",
                    value:"7.19",
                }
            ]                
    },
	{
        "id":"M4",        
        "name":"炳坑院区式小区",
        "jingdu":"114.286517",
        "weidu":"22.695567",
        "nongdu":"66",        
        "describe":"轻微异味",        
        "date":"2018-11-04",
        "wuranwu":[
                {
                    name:"丙醛",
                    value:"2.7",
                },
                {
                    name:"丁醛",
                    value:"94.2",
                },
                {
                    name:"乙酸乙酯",
                    value:"7.9",
                }
            ]                
    },	
	{
        "id":"M5",        
        "name":"亚辉龙生物科技大厦",
        "jingdu":"114.297692",
        "weidu":"22.699484",
        "nongdu":"55",        
        "describe":"轻微异味",        
        "date":"2018-11-05",
        "wuranwu":[
                {
                    name:"丙醛",
                    value:"2.7",
                },
                {
                    name:"丁醛",
                    value:"94.2",
                },
                {
                    name:"乙酸乙酯",
                    value:"7.9",
                }
            ]                
    },	
	{
        "id":"M6",        
        "name":"高帆家私有限公司",
        "jingdu":"114.295357",
        "weidu":"22.692349",
        "nongdu":"44",        
        "describe":"明显的异味",        
        "date":"2018-11-06",
        "wuranwu":[
                {
                    name:"戊醛",
                    value:"2.7",
                },
                {
                    name:"甲基异丁基",
                    value:"94.2",
                },
                {
                    name:"乙酸乙酯",
                    value:"7.9",
                }
            ]                
    },	 
	{
        "id":"M7",        
        "name":"深圳市深安企业有限公司",
        "jingdu":"114.295824",
        "weidu":"22.692649",
        "nongdu":"91",        
        "describe":"油漆的味道",        
        "date":"2018-11-07",
        "wuranwu":[
                {
                    name:"丙醛",
                    value:"1.7",
                },
                {
                    name:"甲基异丁基酮",
                    value:"54.2",
                },
                {
                    name:"乙酸乙酯",
                    value:"6.9",
                }
            ]                
    },		
	{
        "id":"M8",        
        "name":"宝龙东片生活区",
        "jingdu":"114.317455",
        "weidu":"22.693666",
        "nongdu":"88",        
        "describe":"油漆的味道",        
        "date":"2018-11-08",
        "wuranwu":[
                {
                    name:"丙醛",
                    value:"2.3",
                },
                {
                    name:"丙烯酸甲酯",
                    value:"94.2",
                },
                {
                    name:"乙酸乙酯",
                    value:"2.9",
                }
            ]                
    },		
	{
        "id":"M9",        
        "name":"美莲达生物科技园",
        "jingdu":"114.319557",
        "weidu":"22.704486",
        "nongdu":"77",        
        "describe":"油漆的味道",        
        "date":"2018-11-09",
        "wuranwu":[
                {
                    name:"丙醛",
                    value:"1.7",
                },
                {
                    name:"酚类",
                    value:"74.2",
                },
                {
                    name:"乙酸乙酯",
                    value:"7.9",
                }
            ]                
    },		
	{
        "id":"M10",        
        "name":"企岭村院区式管理小区",
        "jingdu":"114.319018",
        "weidu":"22.714087",
        "nongdu":"50",        
        "describe":"油漆的味道",        
        "date":"2018-11-10",
        "wuranwu":[
                {
                    name:"甲基丙烯酸甲酯",
                    value:"5.7",
                },
                {
                    name:"丁醛",
                    value:"34.2",
                },
                {
                    name:"臭气浓度",
                    value:"6.9",
                }
            ]                
    }
]

